global:
  check_interval: 10s
  failure_threshold: 3
  ssh_timeout: 5s
  timeout: 3s

services:
  - name: google
    check_type: http
    target: "www.google.com"

    ssh:
      host: "10.0.0.5"
      port: 22
      user: "deploy"
      key_path: "/home/deploy/.ssh/phoenix_id_ed25519"

    recover:
      strategy: docker_restart
      target: "web-api-container"

  - name: Youtube
    check_type: http
    target: "https://www.youtube.com"
    check_interval: 5s
    failure_threshold: 2

    ssh:
      host: "10.0.0.9"
      port: 22
      user: "deploy"
      key_path: "/home/deploy/.ssh/phoenix_id_ed25519"

    recover:
      strategy: systemd_restart
      target: "worker.service"